services:
  - type: web
    name: ramo-site
    runtime: node
    region: frankfurt
    plan: free
    rootDir: site
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npx prisma db seed && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: JWT_SECRET
        generateValue: true
